language: node_js
node_js:
  - 12
addons:
  firefox: latest
jobs:
  include: 
    - stage: Lint & Unit Tests
      before_script:
        - npm install -g polymer-cli
      script: 
        - npm run lint
      script: 
        - xvfb-run polymer test --module-resolution=node --npm --local firefox
