language: node_js
node_js:
  - 12
addons:
  firefox: latest
jobs:
  include: 
    - stage: Lint & Unit Tests
      before_script:
        - npm install -g polymer-cli
      script: 
        - npm run lint
        - xvfb-run polymer test --module-resolution=node --npm --local firefox
    - stage: Release
      script: skip   # usually you do not want to rerun any tests
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
        on:
          branch: master
