language: node_js
node_js:
  - 11
before_script:
  - npm install -g polymer-cli
  - git checkout package-lock.json
node_js: node
addons:
  chrome: stable
script:
  - xvfb-run polymer test --local chrome
dist: trusty
cache:
  directories:
    - node_modules